language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
env:
  - CODECLIMATE_REPO_TOKEN=7ea75ed73d3f39941fda7d6add302d17564d73ed337b4820cf2c5b16044a37a7
sudo: false
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate < coverage/lcov.info
